---
- hosts: all
  vars:
    packages:
      - "python3"
      - "python3-pip"
      - "python3-dev"
      - "python3-venv"
  tasks:
  - name: Install python3
    apt:
      name: "{{item}}"
      state: installed
    with_items: "{{packages}}"
    become: true