---
- hosts: all
  vars:
    foo: hello
    dir_nvm: /home/vagrant/.nvm
    nvm_ver: 0.33.1
    node_ver: stable

  tasks:
  - name: Download NVM.
    get_url: 
      url: "https://raw.githubusercontent.com/creationix/nvm/v{{nvm_ver}}/install.sh"
      dest: /tmp/install.sh
  
  - name: Install NVM.
    script: /tmp/install.sh
  
  - name: Install node stable.
    shell: bash -c '. ~/.nvm/nvm.sh; nvm install {{node_ver}}'